[workspace]
resolver = "2"
members = ["crates/chigutiro-core", "crates/chigutiro-server"]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["serde", "clock", "std"] }
thiserror = "2"
